### ISSUE TITLE
Disallow '-' for diagram names in wizard

### ISSUE THREAD

**Issue by joehen** [Cooperate-Project/CooperateModelingEnvironment#16]
using a - in the diagram name leads to the following Exception:
java.lang.IllegalArgumentException: The Papyrus diagram name "bre-CD" must not contain the '-' character.
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:155)
	at de.cooperateproject.modeling.textual.common.convetions.ModelNamingConventions.getTextualModelNameObject(ModelNamingConventions.java:87)
	at de.cooperateproject.modeling.textual.common.convetions.ModelNamingConventions.getTextualFromGraphicalURI(ModelNamingConventions.java:50)
	at de.cooperateproject.ui.wizards.modelnew.ModelCreator.createTextualModel(ModelCreator.java:159)
	at de.cooperateproject.ui.wizards.modelnew.ModelCreator.createModel(ModelCreator.java:88)
	at de.cooperateproject.ui.wizards.modelnew.ModelCreator.createDiagram(ModelCreator.java:60)
	at de.cooperateproject.ui.wizards.modelnew.NewClassDiagramWizard.performFinish(NewClassDiagramWizard.java:40)
...

**Comment by seiferma** [comment]
We should disallow special chars that can mess up the diagram title in the textual diagram as well. I will restrict the diagram title to the regular expression `[a-Z0-9 _]+`. This should prohibit most issues without restricting the user too much.
