### ISSUE TITLE
CoreException when deleting elements in graphical editor

### ISSUE THREAD

**Issue by FPersch** [Cooperate-Project/CooperateModelingEnvironment#18]
Trying to save a diagram after deleting an element in the graphical editor leads to the following exception:

> 3    [CDOViewInvalidationRunner-View 3 [MAIN]] WARN  de.cooperateproject.ui.nature.tasks.ModelGenCheckoutTask  - Full checkout did not succeed after a change in CDO has been detected.
org.eclipse.core.runtime.CoreException: Failed to transfer models
	at de.cooperateproject.ui.nature.tasks.ModelGenCheckoutTask.doFullCheckout(ModelGenCheckoutTask.java:79)
	at de.cooperateproject.ui.nature.tasks.ModelGenCheckoutTask.handleChange(ModelGenCheckoutTask.java:38)
	at de.cooperateproject.ui.nature.tasks.CDOHandlingBackgroundTask$ChangeListener.notifyEvent(CDOHandlingBackgroundTask.java:35)
	at org.eclipse.net4j.util.event.Notifier.fireEventSafe(Notifier.java:167)
	at org.eclipse.net4j.util.event.Notifier.fireEvent(Notifier.java:113)
	at org.eclipse.emf.internal.cdo.view.CDOViewImpl.fireInvalidationEvent(CDOViewImpl.java:1296)
	at org.eclipse.emf.internal.cdo.view.CDOViewImpl.doInvalidateSynced(CDOViewImpl.java:1210)
	at org.eclipse.emf.internal.cdo.view.CDOViewImpl.doInvalidate(CDOViewImpl.java:1171)
	at org.eclipse.emf.internal.cdo.view.CDOViewImpl$InvalidationRunnable.doRun(CDOViewImpl.java:2775)
	at org.eclipse.net4j.util.concurrent.RunnableWithName.run(RunnableWithName.java:46)
	at org.eclipse.net4j.util.concurrent.ExecutorWorkSerializer$1.run(ExecutorWorkSerializer.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Could not serialize EObject via backtracking.

**Comment by seiferma** [comment]
I cannot reproduce this issue in my environment. Could you provide me with some example models?

**Comment by FPersch** [comment]
Steps to reproduce:
- create class
- save
- delete class
- save
- get exception

**Comment by seiferma** [comment]
I reproduced the issue. The issue is caused by a combination of stale references and orphaned elements after removals. I added some processors that handle the issues but they are not complete with respects to element types that can be deleted.

Please test the fix and report if the issue is actually fixed.

**Comment by seiferma** [comment]
I fixed a concurrent modification exception. Would you mind to test the fix again?

**Comment by FPersch** [comment]
Cannot reproduce the error anymore.
