### ISSUE TITLE
Opening a second read-only editor on same repo creates exception

### ISSUE THREAD

**Issue by joehen** [Cooperate-Project/CooperateModelingEnvironment#235]
```
[ERROR] A view to cdo://repo1 is already attached to the resource set
java.lang.RuntimeException: A view to cdo://repo1 is already attached to the resource set
	at org.eclipse.emf.internal.cdo.view.CDOViewSetImpl.add(CDOViewSetImpl.java:163)
	at org.eclipse.emf.internal.cdo.session.CDOViewContainerImpl.initView(CDOViewContainerImpl.java:270)
	at org.eclipse.emf.internal.cdo.session.CDOViewContainerImpl.openView(CDOViewContainerImpl.java:137)
	at org.eclipse.emf.internal.cdo.session.CDOViewContainerImpl.openView(CDOViewContainerImpl.java:125)
	at org.eclipse.emf.cdo.internal.explorer.checkouts.CDOCheckoutImpl.doOpenView(CDOCheckoutImpl.java:630)
	at org.eclipse.emf.cdo.internal.explorer.checkouts.CDOCheckoutImpl.openAndConfigureView(CDOCheckoutImpl.java:610)
	at org.eclipse.emf.cdo.internal.explorer.checkouts.CDOCheckoutImpl.openView(CDOCheckoutImpl.java:590)
	at org.eclipse.papyrus.cdo.internal.ui.customization.properties.storage.CDOContextStorageProvider$1.notifyEvent(CDOContextStorageProvider.java:78)
	at org.eclipse.net4j.util.event.Notifier.fireEventSafe(Notifier.java:167)
	at org.eclipse.net4j.util.event.Notifier.fireEvent(Notifier.java:113)
	at org.eclipse.net4j.util.event.Notifier.fireEvent(Notifier.java:89)
	at org.eclipse.net4j.util.container.Container.fireEvent(Container.java:62)
	at org.eclipse.emf.cdo.internal.explorer.checkouts.CDOCheckoutManagerImpl.fireCheckoutOpenEvent(CDOCheckoutManagerImpl.java:88)
	at org.eclipse.emf.cdo.internal.explorer.checkouts.CDOCheckoutImpl.open(CDOCheckoutImpl.java:463)
	at de.cooperateproject.ui.editors.launcher.extensions.EditorLauncherBase.createCheckout(EditorLauncherBase.java:309)
	at de.cooperateproject.ui.editors.launcher.extensions.EditorLauncherBase.<init>(EditorLauncherBase.java:91)
	at de.cooperateproject.ui.textualeditors.editorlauncher.TextualCDOEditorLauncher.<init>(TextualCDOEditorLauncher.java:45)
	at de.cooperateproject.ui.textualeditors.editorlauncher.TextualCDOEditorLauncherFactory.create(TextualCDOEditorLauncherFactory.java:30)
	at de.cooperateproject.ui.editors.launcher.EditorLauncher.open(EditorLauncher.java:68)
```

**Comment by seiferma** [comment]
I opened three textual editor on the same model. I could not reproduce the error. Did you use different models?

**Comment by joehen** [comment]
I used the same model and got the warning that it is only a read only editor
