### ISSUE TITLE
Editing/Deleting comments in textual diagrams

### ISSUE THREAD

**Issue by larissaschmid** [Cooperate-Project/CooperateModelingEnvironment#254]
After editing or deleting comments in textual diagrams and saving, the following error message is shown and the whole text is underlined red.
> org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy  - Error post-processing resource with content. 
org.eclipse.emf.cdo.util.DanglingReferenceException: The object "CDOLegacyAdapter[CSSShapeImpl@null](org.eclipse.emf.internal.cdo.object.CDOLegacyAdapter)" is not contained in a resource
	at org.eclipse.emf.internal.cdo.view.AbstractCDOView.provideCDOID(AbstractCDOView.java:2186)
	at org.eclipse.emf.internal.cdo.transaction.CDOTransactionImpl.provideCDOID(CDOTransactionImpl.java:3473)
	at org.eclipse.emf.cdo.internal.common.revision.delta.CDOSingleValueFeatureDeltaImpl.writeValue(CDOSingleValueFeatureDeltaImpl.java:90)
...

Although the transformation to the graphical diagram is correct and faultless.

**Comment by seiferma** [comment]
Add a quick fix for adjusting the comment body if there is already a comment attached to the element.
