### ISSUE TITLE
Revert to commit fails in some situations

### ISSUE THREAD

**Issue by seiferma** [Cooperate-Project/CooperateModelingEnvironment#262]
Revert to commit fails sometimes because not all resources could be saved.

```
java.net.UnknownServiceException: protocol doesn't support output
	at java.net.URLConnection.getOutputStream(URLConnection.java:843)
	at org.eclipse.emf.ecore.resource.impl.URIHandlerImpl.createOutputStream(URIHandlerImpl.java:154)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createOutputStream(ExtensibleURIConverterImpl.java:349)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.save(ResourceImpl.java:996)
	at de.cooperateproject.ui.commands.ResetToPreviousStateCommand.reset(ResetToPreviousStateCommand.java:216)
	at de.cooperateproject.ui.commands.ResetToPreviousStateCommand.reset(ResetToPreviousStateCommand.java:137)
	at de.cooperateproject.ui.commands.ResetToPreviousStateCommand.reset(ResetToPreviousStateCommand.java:91)
	at de.cooperateproject.ui.commands.ResetToPreviousStateCommand.reset(ResetToPreviousStateCommand.java:56)
	at de.cooperateproject.ui.diff.views.DiffView$3.run(DiffView.java:222)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
```

**Comment by seiferma** [comment]
The issue is caused by a read only resource (primitive types model) in the resource set that is about to be saved. The resolution is just not saving resources that have been inserted because of resolution process.
