### ISSUE TITLE
NPE in ErrorSignalContext if no signalization activated

### ISSUE THREAD

**Issue by seiferma** [Cooperate-Project/CooperateModelingEnvironment#29]
The ErrorSignalContext throws a NullPointerException if no signalization is enabled:
```
java.lang.NullPointerException
	at de.cooperateproject.modeling.textual.xtext.runtime.editor.errorsignalization.ErrorSignalContext.createSignal(ErrorSignalContext.java:40)
	at de.cooperateproject.modeling.textual.xtext.runtime.editor.CooperateCDOXtextEditor.handleCursorPositionChanged(CooperateCDOXtextEditor.java:64)
	at org.eclipse.ui.texteditor.AbstractTextEditor$4.mouseUp(AbstractTextEditor.java:3122)
```

**Comment by seiferma** [comment]
Sorry, got an somehow outdated version. Everything works fine.
