### ISSUE TITLE
Tailor Papyrus UI to capabilities of textual notation

### ISSUE THREAD

**Issue by seiferma** [Cooperate-Project/CooperateModelingEnvironment#6]
Papyrus is the graphical editor of the modeling environment and provides almost all modeling capabilities of UML. Our textual notation is some sort of simplified concrete syntax of UML. We have to prohibit modeling of unsupported elements and features in Papyrus. This requires two parts:
* Provide a reduced UI that contains only the supported elements
* Provide validators that ensure that no unsupported elements are contained in the graphical diagram

Hints on how to adjust the Papyrus UI can be found in the [Papyrus Wiki](https://wiki.eclipse.org/Papyrus_for_Information_Modeling/Customization_Guide#Papyrus_Customization).

**Comment by seiferma** [comment]
I experienced the following issue. Please, have a look at it.

```
java.lang.NullPointerException
	at org.eclipse.core.runtime.Path.<init>(Path.java:228)
	at org.eclipse.core.runtime.Path.<init>(Path.java:186)
	at de.cooperateproject.modeling.graphical.papyrus.extensions.validation.CooperateClientSelector.selects(CooperateClientSelector.java:23)
	at org.eclipse.emf.validation.internal.service.ClientContextManager.getClientContextsFor(ClientContextManager.java:183)
	at org.eclipse.emf.validation.internal.service.LiveValidator.doValidate(LiveValidator.java:95)
	at org.eclipse.emf.validation.internal.service.AbstractValidator.validate(AbstractValidator.java:147)
	at org.eclipse.emf.transaction.impl.ReadWriteValidatorImpl.validate(ReadWriteValidatorImpl.java:221)
	at org.eclipse.emf.transaction.impl.TransactionImpl.validate(TransactionImpl.java:767)
	at org.eclipse.emf.transaction.impl.TransactionImpl.commit(TransactionImpl.java:429)
	at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:155)
	at org.eclipse.gmf.runtime.diagram.ui.commands.SemanticCreateCommand.doExecuteWithResult(SemanticCreateCommand.java:91)
	at org.eclipse.gmf.runtime.common.core.command.AbstractCommand.execute(AbstractCommand.java:134)
	at org.eclipse.gmf.runtime.common.core.command.CompositeCommand.doExecuteWithResult(CompositeCommand.java:403)
	at org.eclipse.gmf.runtime.common.core.command.AbstractCommand.execute(AbstractCommand.java:134)
	at org.eclipse.gmf.runtime.common.core.command.CompositeCommand.doExecuteWithResult(CompositeCommand.java:403)
...
```

**Comment by seiferma** [comment]
Please enforce the following constraints:
- A comment must not annotate more than one element
- A comment must only comment interfaces, classes, or associations
- Names must not contain spaces (they have to match [a-Z][a-Z0-9]*)
- Names of classes or interfaces might have spaces but there has to be a name expression, whichs name matches the regex defined above
- Attributes must have a type
- Parameters must have a type

**Comment by PhilippFaller** [comment]
Still to do:
- A comment must not annotate more than one element
- A comment must only comment interfaces, classes, or associations
- Names must not contain spaces (they have to match [a-Z][a-Z0-9]*)
- Names of classes or interfaces might have spaces but there has to be a name expression, whichs name matches the regex defined above
- Attributes must have a type
- Parameters must have a type
