### ISSUE TITLE
ClassCastException in Content Outline

### ISSUE THREAD

**Issue by PhilippFaller** [Cooperate-Project/CooperateModelingEnvironment#67]
The following steps provoke a ClassCastException:

1. Open graphical editor
2. Create new class
3. Click on class in outline

> org.eclipse.ui.views.contentoutline.ContentOutline cannot be cast to org.eclipse.ui.views.properties.tabbed.ITabbedPropertySheetPageContributor
	at org.eclipse.papyrus.infra.properties.ui.xwt.XWTTabDescriptorProvider.getTabDescriptors(XWTTabDescriptorProvider.java:199)
	at org.eclipse.ui.internal.views.properties.tabbed.view.TabbedPropertyRegistry.getTabDescriptors(TabbedPropertyRegistry.java:287)
	at org.eclipse.ui.views.properties.tabbed.TabbedPropertySheetPage.setInput(TabbedPropertySheetPage.java:729)
	at org.eclipse.ui.views.properties.tabbed.TabbedPropertySheetPage.selectionChanged(TabbedPropertySheetPage.java:555)
	at org.eclipse.papyrus.infra.ui.editor.MultiDiagramPropertySheetPage.selectionChanged(MultiDiagramPropertySheetPage.java:116)
	at org.eclipse.ui.views.properties.PropertySheet.showSelectionAndDescription(PropertySheet.java:491)
	at org.eclipse.ui.views.properties.PropertySheet.selectionChanged(PropertySheet.java:471)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:259)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:194)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:211)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:250)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:247)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:757)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:682)
	at org.eclipse.e4.ui.internal.workbench.swt.AbstractPartRenderer.activate(AbstractPartRenderer.java:95)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer$1.handleEvent(ContributedPartRenderer.java:63)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1542)
	at org.eclipse.swt.widgets.Shell.WM_MOUSEACTIVATE(Shell.java:2467)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4843)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1656)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2199)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4897)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4897)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4897)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4897)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4897)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4897)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4897)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4897)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4897)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4897)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.CallWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(OS.java:2446)
	at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1552)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4897)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6074)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.PeekMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.PeekMessage(OS.java:3144)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3819)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

**Comment by PhilippFaller** [comment]
Is the FIXME in Line 112 of [XWTTabDescriptorProvider ](https://git.eclipse.org/c/papyrus/org.eclipse.papyrus.git/tree/plugins/views/properties/org.eclipse.papyrus.views.properties/src/org/eclipse/papyrus/views/properties/xwt/XWTTabDescriptorProvider.java?id=8df0650d9e42efb4a70a04cab70d7a0fd3e88095) related to this bug?

**Comment by seiferma** [comment]
The exception is definitely an issue of the Papyrus code base. I filed an issue for this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=519850

However, I added a workaround and the exception does not occur anymore.
